version: '2'
services:
  nginx:
    image: nginx:latest 
    ports:
     - 80:80
    volumes:
     - ./build:/usr/share/nginx/html/build
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: /bin/bash -c "nginx -g 'daemon off;'"